### ISSUE TITLE
Consider refactor logging

### ISSUE THREAD

**Issue by tomschr** [liangxin1300/cluster_preflight_check#12]
## Problem

The file `cluster_preflight_check/main.py` contains the function `setup_logging` which, well, setups the logging module.

However, this setup contains some issues:

* Your setup configures the root logger. This is not really a bad thing, but if you use this project as a library later, it can make maintenance a lot harder.
* You manually create the logger. Although this is also not a bad thing, you gain much more flexibility if you consider to use a INI file or a dictionary, see my [Gist](https://gist.github.com/tomschr/10837c2f7286b13d3ebc59e40d943188).
* The comment `setting handler for stdout` is wrong. You normally log to stderr, not stdout.

## Benefits

* When implementing this issue, logging is much more flexible
* You can configure your logging to log do a different source, for example (if you wish).
* A hierarchy of loggers can be helpful to have only dedicated output. 
* Logging can be selectively silenced, depending on the logger name
* With different loggers, you can identify sbd from corosync related messages.
* Easier maintenance

## Suggested Solution

* Use a dedicated name for your logger, for example `cpc` short for "cluster preflight check":

    ```python
    log = logger.getLogger('cpc')
    ```

   Theoretically, you could also use `__name__` instead of `cpc`, but that gives you the very long name `cluster_preflight_test` which could make the logging output a bit long.

   Use this name in all of your module files to get the logger instance.

* As suggested in the [Hitchhiker's Guide to Python](https://docs.python-guide.org/writing/logging/#logging-in-a-library), place a NullHandler in `__init__.py`:

    ```python
    # Set default logging handler to avoid "no handler found" warnings
    import logging
    try:
        from logging import NullHandler
    except ImportError:
        class NullHandler(logging.Handler):
            def emit(self, record):
                pass

    logging.getLogger('cpc').addHandler(NullHandler())
    ```

* If you need to distinguish between output from sbd, corosync, or other services, you can create hierarchy loggers. For example:

    ```python
    sbdlog = logger.getLogger('cpc.sbd')
    corolog = logger.getLogger('cpc.corosync')
    # ...

    sbdlog.info("This output is from sbd")
    corolog.info("This output is from corosync")
    ```

    Not sure if you really want to go that deep, but I just mention it in case it's a usecase for you.

* Use an INI file, if you want to make logging configuration much more flexible, see [Example Configuration via an INI File](https://docs.python-guide.org/writing/logging/#example-configuration-via-an-ini-file)

**Comment by liangxin1300** [comment]
Hi @tomschr ,
Big thanks for your suggestion, I will consider it and try to make the log more flexible:)

**Comment by tomschr** [comment]
@liangxin1300 you're welcome. Hope it didn't sound to harsh, my only intention was to help you. :-)

If you need further help, just ping me.
