### ISSUE TITLE
Check explicitly for user root

### ISSUE THREAD

**Issue by tomschr** [liangxin1300/cluster_preflight_check#7]
## Problem

If a normal user passed the command line parsing, the user get a confusing PermissionError (see #6).

## Expected Solution

If the current user is not root, the script should abort and give a meaningful error message, for example:

```
This script can only be executed as user root.
```

(Just an example).

The current user can be checked with `os.getuid()`.

**Comment by liangxin1300** [comment]
Thanks for using!
I have created a PR for this, in #8 , please review:)
